#!/bin/bash

#
# A really weak bash script to quickly stand up an elasticsearch dev sysystem
#
# Remember to change VOLUME_PATH

VOLUME_PATH="/tmp/docker"

# Elasticsearch settings
ESIMAGE="docker.elastic.co/elasticsearch/elasticsearch:6.2.2"
ESVOL="-v ${VOLUME_PATH}/elastic-data:/usr/share/elasticsearch/data"
#ESPLUG='-v ${VOLUME_PATH}/elastic-plugins:/usr/share/elasticsearch/plugins'
ESPLUG=""

# Kibana settings
KIBANAIMAGE="docker.elastic.co/kibana/kibana:6.2.2"
#KIBVOL='-v ${VOLUME_PATH}/kibana-plugins:/usr/share/kibana/plugins'
KIBVOL=""

# Logstash settings
LOGSTASHIMAGE="docker.elastic.co/logstash/logstash:6.2.2"
STASHCONFIG="-v ${VOLUME_PATH}/logstash/:/usr/share/logstash/pipeline/ -v ${VOLUME_PATH}/logstash-logs:/var/log/logstash"

# Filebeat settings
FILEBEATIMAGE="docker.elastic.co/filebeats/filebeats:6.2.2"
FBLOGS="-v ${VOLUME_PATH}/filebeat/filebeat.yml:/filebeat.yml -v ${VOLUME_PATH}/filebeat:/var/lib/filebeat/"

function stop_dc
{
    echo -n "Stopping $1... "
    docker stop $1 > /dev/null 2>&1
    docker rm $1 > /dev/null 2>&1
    echo "[DONE]"
}

function start_dc
{
    CONTAINER="$1"
    if [ -z "`docker ps -qf name=${CONTAINER}`" ]; then 
        echo -n "Starting ${CONTAINER}... "
        docker rm $CONTAINER > /dev/null 2>&1

        case "$CONTAINER" in
            elasticsearch)
                docker run --name elasticsearch -d $ESVOL $ESPLUG -p 9200:9200 $ESIMAGE  > /dev/null 2>&1
                ;;
            logstash)
                docker run --name logstash -d --link elasticsearch:elasticsearch -p 5044:5044 -p 5144:5144/udp $STASHCONFIG $LOGSTASHIMAGE > /dev/null 2>&1
                ;;
            kibana)
                docker run --name kibana -d --link elasticsearch:elasticsearch -p 5601:5601 $KIBVOL $KIBANAIMAGE > /dev/null 2>&1
                ;;
            filebeat)
                docker run --name filebeat --link elasticsearch:elasticsearch --link logstash:logstash -d $FBLOGS $FILEBEATIMAGE > /dev/null 2>&1
                ;;
            grafana)
                docker run --name grafana -d --link elasticsearch:elasticsearch -e "GF_SECURITY_ADMIN_PASSWORD=admin" -p 3000:3000 grafana/grafana:master > /dev/null 2>&1
                ;;
        esac
        echo "[DONE]"
    fi
   
}


function start_container {
    case "$1" in
        elastic)
            start_dc elasticsearch
            ;;
        logstash)
            start_dc logstash
            ;;
        kibana)
            start_dc kibana
            ;;
        filebeat)
            start_dc filebeat
            ;;
        grafana)
            start_dc grafana
            ;;
        all)
            start_dc elasticsearch
            start_dc logstash
            start_dc kibana
            start_dc grafana
            #start_filebeat
            ;;
        *)
            echo "Give me a service (elastic, logstash, kibana, filebeat, all)"
    esac
}

function stop_container {
    case "$1" in
        elastic)
            stop_dc elasticsearch
            ;;
        logstash)
            stop_dc logstash
            ;;
        kibana)
            stop_dc kibana
            ;;
        filebeat)
            stop_dc filebeat
            ;;
        grafana)
            stop_dc grafana
            ;;
        all)
            stop_dc elasticsearch
            stop_dc logstash
            stop_dc kibana
            stop_dc grafana
            #stop_filebeat
            ;;
        *)
            echo "Give me a service (elastic, logstash, kibana, filebeat, all)"
    esac
}

function get_index {
    curl -XGET "http://elastic:changeme@localhost:9200/_cat/indices"
}

function delete_index {
    curl -XDELETE "http://elastic:changeme@localhost:9200/$1"
}

function status {
    echo -n "Elasticsearch...    "
    if [ -z "`docker ps -qf name=elasticsearch`" ]; then 
        echo "[STOPPED]"
    else
        echo "[RUNNING]"
    fi

    echo -n "Logstash...         "
    if [ -z "`docker ps -qf name=logstash`" ]; then 
        echo "[STOPPED]"
    else
        echo "[RUNNING]"
    fi

    echo -n "Kibana...           "
    if [ -z "`docker ps -qf name=kibana`" ]; then 
        echo "[STOPPED]"
    else
        echo "[RUNNING]"
    fi

    echo -n "Grafana...           "
    if [ -z "`docker ps -qf name=grafana`" ]; then 
        echo "[STOPPED]"
    else
        echo "[RUNNING]"
    fi

    echo -n "Filebeat...         "
    if [ -z "`docker ps -qf name=filebeat`" ]; then 
        echo "[STOPPED]"
    else
        echo "[RUNNING]"
    fi
}

case "$1" in
    start)
        start_container $2
        ;;
    stop)
        stop_container $2
        ;;
    index)
        case "$2" in
            delete) 
                delete_index $3
                ;;
            list)
                get_index
                ;;
            *)
                echo "index delete (name) | index list"
        esac
        ;;
    status)
        status
        ;;
    restart)
        stop_container $2
        start_container $2
        ;;
    *)
        echo "start | stop | restart | status | index"
esac
